package com.gymapp.gymapp.Service;

import com.gymapp.gymapp.Entities.Trainer;
import com.gymapp.gymapp.Repository.TrainerRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import java.util.Collection;
import java.util.Map;
import java.util.Optional;

@Service
public class TrainerService {

    @Autowired
    private TrainerRepository repository;

    // Retrieve all trainers from the database
    public Collection<Trainer> getAllTrainers() {
        return repository.findAll();
    }

    // Find a trainer by ID using Optional to handle nulls safely
    public Trainer getTrainerById(Long id) {
        return repository.findById(id).orElse(null);
    }

    // Save a new trainer (ID is auto-generated by DB)
    public Trainer createTrainer(Trainer trainer) {
        return repository.save(trainer);
    }

    // Update an existing trainer
    public Trainer updateTrainer(Long id, Trainer updatedTrainer) {
        if (repository.existsById(id)) {
            updatedTrainer.setId(id);
            return repository.save(updatedTrainer);
        }
        return null;
    }

    // Delete a trainer by ID
    public void deleteTrainer(Long id) {
        repository.deleteById(id);
    }

    // Apply partial updates to a trainer entity
    public Trainer patchTrainer(Long id, Map<String, Object> updates) {
        Optional<Trainer> op = repository.findById(id);

        if (op.isPresent()) {
            Trainer trainer = op.get();
            if (updates.containsKey("name"))
                trainer.setName((String) updates.get("name"));
            if (updates.containsKey("email"))
                trainer.setEmail((String) updates.get("email"));
            if (updates.containsKey("description"))
                trainer.setDescription((String) updates.get("description"));
            if (updates.containsKey("imageUrl"))
                trainer.setImageUrl((String) updates.get("imageUrl"));
            return repository.save(trainer);
        }
        return null;
    }
}