package com.gymapp.gymapp.Service;

import com.gymapp.gymapp.Entities.Trainer;
import com.gymapp.gymapp.Repository.TrainerRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import java.util.Collection;
import java.util.Map;
import java.util.Optional;
import org.springframework.lang.NonNull;

@Service
public class TrainerService {

    @Autowired
    private TrainerRepository trainerRepository;

    // Retrieve all trainers from the database
    public Collection<Trainer> getAllTrainers() {
        return trainerRepository.findAll();
    }

    // Find a trainer by ID using Optional to handle nulls safely
    public Trainer getTrainerById(@NonNull Long id) {
        return trainerRepository.findById(id).orElse(null);
    }

    // Save a new trainer (ID is auto-generated by DB)
    public Trainer createTrainer(@NonNull Trainer trainer) {
        return trainerRepository.save(trainer);
    }

    // Update an existing trainer
    public Trainer updateTrainer(@NonNull Long id, @NonNull Trainer updatedTrainer) {
        if (trainerRepository.existsById(id)) {
            updatedTrainer.setId(id);
            return trainerRepository.save(updatedTrainer);
        }
        return null;
    }

    // Delete a trainer by ID
    public void deleteTrainer(@NonNull Long id) {
        trainerRepository.deleteById(id);
    }

    // Apply partial updates to a trainer entity
    public Trainer patchTrainer(@NonNull Long id, Map<String, Object> updates) {
        // Find the trainer by ID
        Optional<Trainer> op = trainerRepository.findById(id);

        // Check if the trainer exists
        if (op.isPresent()) {
            // Get the trainer from the Optional
            Trainer trainer = op.get();

            // Apply updates to the trainer entity
            if (updates.containsKey("name"))
                trainer.setName((String) updates.get("name"));
            if (updates.containsKey("email"))
                trainer.setEmail((String) updates.get("email"));
            if (updates.containsKey("description"))
                trainer.setDescription((String) updates.get("description"));
            if (updates.containsKey("imageUrl"))
                trainer.setImageUrl((String) updates.get("imageUrl"));

            // Save the updated trainer
            return trainerRepository.save(trainer);
        }
        return null;
    }
}